### ISSUE TITLE
can't build with nginx-1.12.2

### ISSUE THREAD

**Issue by dekuznetsov** [qiankunli/nginx-upsync-module-zk#1]
```
/usr/local/src/nginx/nginx-upsync-module-zk/src/ngx_http_upsync_module.c:3406:1: error: conflicting types for ‘ngx_strnlen’
 ngx_strnlen(const char *s, size_t maxlen)
 ^
In file included from src/core/ngx_core.h:50:0,
                 from /usr/local/src/nginx/nginx-upsync-module-zk/src/ngx_http_upsync_module.c:7:
src/core/ngx_string.h:63:8: note: previous declaration of ‘ngx_strnlen’ was here
 size_t ngx_strnlen(u_char *p, size_t n);
        ^
objs/Makefile:1841: recipe for target 'objs/addon/src/ngx_http_upsync_module.o' failed

```

patch for fix build:
```
diff --git a/src/ngx_http_upsync_module.c b/src/ngx_http_upsync_module.c
index bee1e30..b9adebc 100644
--- a/src/ngx_http_upsync_module.c
+++ b/src/ngx_http_upsync_module.c
@@ -3403,7 +3403,7 @@ ngx_http_upsync_del_delay_delete(ngx_event_t *event)
 
 
 static size_t
-ngx_strnlen(const char *s, size_t maxlen)
+ngx_zk_strnlen(const char *s, size_t maxlen)
 {
     const char *p;
 
@@ -3424,8 +3424,8 @@ ngx_strlncat(char *dst, size_t len, const char *src, size_t n)
     size_t rlen;
     size_t ncpy;
 
-    slen = ngx_strnlen(src, n);
-    dlen = ngx_strnlen(dst, len);
+    slen = ngx_zk_strnlen(src, n);
+    dlen = ngx_zk_strnlen(dst, len);
 
     if (dlen < len) {
         rlen = len - dlen;

```
